export function SetGirlPreset() {
    const preset: any = { "cutom-color-param_currentWeatherWindBgColor_": "#fe73f2", "cutom-color-param_currentWeatherPrecipitationProbMaxTextColor_": "rgb(255, 255, 255)", "cutom-color-param_currentAppearentWeatherTempTextColor_": "#dfaff8", "cutom-color-param_hourlyAppearentTempText_": "#f1adff", "cutom-color-param_WeatherCodeIconColor_": "#a09eff", "cutom-color-param_hourlyTempText_": "#ffffff", "cutom-color-param_hourlyCardBg_": "linear-gradient(0deg, #992fa7, #c45ac0)", "cutom-color-param_currentDateTextColor_": "#fff6c7", "cutom-color-param_currentWeatherSunsetColor_": "#232970", "cutom-color-param_currentWeatherCardBg_": "linear-gradient(45deg, #a21590, #d378d2)", "cutom-color-param_hourlyWeathercode_": "#ffffff", "cutom-color-param_currentWeatherSunriseColor_": "#b0ff70", "cutom-color-param_currentWeatherWindTextColor_": "rgb(255, 255, 255)", "cutom-color-param_currentWeatherPrecipitationBgColor_": "#fe73f2", "cutom-color-param_currentWeatherCityColor_": "#e3aeea", "cutom-color-param_currentWeatherPrecipitationTextColor_": "rgb(255, 255, 255)", "cutom-color-param_BGCOLOR_": "linear-gradient(130deg, #8a2884, #c752bd)", "cutom-color-param_currentWeatherCelsiumColor_": "#e3aeea", "cutom-color-param_currentWeatherHumidityTextColor_": "rgb(255, 254, 253)", "cutom-color-param_currentWeatherTempColor_": "#e3aeea", "cutom-color-param_hourlyDateText_": "#e8bdff", "cutom-color-param_hourlyHumidityText_": "#95c3ff", "cutom-color-param_currentWeatherPrecipitationProbMaxBgColor_": "#fe73f2", "cutom-color-param_currentWeatherHumidityBgColor_": "#fe73f2" }
    setPreset(preset)
}

export function setCatShopPresets() {
    const preset: any = { "cutom-color-param_currentWeatherWindBgColor_": "#5e9bff4a", "cutom-color-param_currentWeatherPrecipitationProbMaxTextColor_": "rgb(255, 255, 255)", "cutom-color-param_currentAppearentWeatherTempTextColor_": "#89dfff", "cutom-color-param_hourlyAppearentTempText_": "#89dfff", "cutom-color-param_WeatherCodeIconColor_": "#44c5dd", "cutom-color-param_hourlyTempText_": "#ffffff", "cutom-color-param_hourlyCardBg_": "linear-gradient(-45deg, #3d3dc0b0, #58b2cd94 70%)", "cutom-color-param_currentDateTextColor_": "#59eeffc7", "cutom-color-param_currentWeatherSunsetColor_": "#b2c6ff", "cutom-color-param_currentWeatherCardBg_": "linear-gradient(0deg, #6771b194, #4946a27d)", "cutom-color-param_hourlyWeathercode_": "#ffffff", "cutom-color-param_currentWeatherSunriseColor_": "#fae79d", "cutom-color-param_currentWeatherWindTextColor_": "rgb(255, 255, 255)", "cutom-color-param_currentWeatherPrecipitationBgColor_": "#5e9bff4a", "cutom-color-param_currentWeatherCityColor_": "#ffffffcf", "cutom-color-param_currentWeatherPrecipitationTextColor_": "rgb(255, 255, 255)", "cutom-color-param_BGCOLOR_": "url('https://img2.akspic.ru/crops/4/0/1/1/7/171104/171104-anime-art-illustracia-artist-rastenie-3840x2160.jpg')", "cutom-color-param_currentWeatherCelsiumColor_": "rgb(255, 255, 255)", "cutom-color-param_currentWeatherHumidityTextColor_": "rgb(255, 254, 253)", "cutom-color-param_currentWeatherTempColor_": "#ffffff", "cutom-color-param_hourlyDateText_": "#ffffff", "cutom-color-param_hourlyHumidityText_": "#95c3ff", "cutom-color-param_currentWeatherPrecipitationProbMaxBgColor_": "#5e9bff4a", "cutom-color-param_currentWeatherHumidityBgColor_": "#5e9bff4a" }
    setPreset(preset);
}

function setPreset(preset: any) {
    Object.keys(preset).forEach(key => {
        window.localStorage.setItem(key, preset[key])
    });
    document.location.reload();
}